Prioritizing CDS array and saving genome through GFU
kbaseapps/kb_plant_rast pull request #4
Opened 2018-05-24 17:49 UTC by samseaver

2018-05-24 17:54 UTC, JamesJeffryes approved these changes

2018-05-24 17:56 UTC, JamesJeffryes reviewed
So this will give new functions to the CDSs but some tools only look at gene functions. You might want to consider propagating annotations to the genes

2018-05-24 18:27 UTC, samseaver commented
@JamesJeffryes Latest commit is to assign CDS function to gene function

2018-05-25 20:35 UTC, JamesJeffryes commented on lib/kb_plant_rast/kb_plant_rastImpl.py
> +            for i in range(len(plant_genome['data']['features'])):
One line option: parent_feature_index = dict([(f['id'], i) for i, f in plant_genome['data']['features']])

2018-05-25 20:36 UTC, JamesJeffryes commented on lib/kb_plant_rast/kb_plant_rastImpl.py
> +                                                'data' : plant_genome['data']});
Add `'upgrade' = 1` to the params.

2018-05-25 20:39 UTC, JamesJeffryes requested changes

2018-05-25 20:39 UTC, JamesJeffryes commented on lib/kb_plant_rast/kb_plant_rastImpl.py
> +        USE_CDS=1
Only use ALL_CAPS for globals set once not flags

2018-05-25 21:17 UTC, merged